### ISSUE TITLE
FQDN en CN y subjectAlternateName:DNS

### ISSUE THREAD

**Issue by morenodelhoyo** [rediris-es/eap_cert_generator#5]
Tras prueba desde CAT, se devuelve este mensaje de información:

The configured EAP server name matches either the CN or a subjectAltName:DNS of the incoming certificate; best current practice is that the certificate should contain the name in BOTH places.

**Comment by lonoak** [comment]
Como hemos comentado, hay que cambiar simplemente el `eduroam.fqdn` por `radius.fqdn`.

**Comment by morenodelhoyo** [comment]
Issue resuelta modificando el fichero server.cnf.tmpl
